version: "3.8"

services:
  db:
    container_name: postgres-docker
    image: postgres
    restart: always
    environment:
      - TZ=Asia/Singapore
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=clettr_db
    ports:
      - "5432:5432"
  pgadmin:
    container_name: pgadmin-docker
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
  redis:
    container_name: redis-docker
    image: redis
    restart: always

    ports:
      - "6379:6379"
